name: Tests de XBank

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Esta es la línea mágica que le dice a GitHub dónde está tu proyecto
    defaults:
      run:
        working-directory: ./minibancodigital
        
    steps:
    - uses: actions/checkout@v4
    - name: Usar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Instalar dependencias
      run: npm install
    - name: Ejecutar Vitest
      # En entornos CI, a veces es más seguro correr el run explícito
      run: npx vitest run